{% set name = "JIGSAW" %}
{% set version = "0.9.15.rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/dengwirda/jigsaw.git
  git_rev: master

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

test:
  source_files:
    - example.jig
    - geo/bunny.msh
    - out/.keep
  commands:
    - jigsaw example.jig

about:
  home: https://github.com/dengwirda/jigsaw
  license: custom
  license_file: LICENSE.md
  summary: |
    JIGSAW is a Delaunay-based unstructured mesh generator for two- and
    three-dimensional geometries.
  description: |
    `JIGSAW` is an unstructured mesh generator and tessellation library; 
    designed to generate high-quality triangulations and polyhedral 
    decompositions of general planar, surface and volumetric domains. 
    `JIGSAW` includes refinement-based algorithms for the construction 
    of new meshes, optimisation-driven techniques for the improvement of 
    existing grids, as well as routines to assemble (restricted) Delaunay 
    tessellations, Voronoi complexes and Power diagrams. 

    This package provides the underlying `c++` source for `JIGSAW`; 
    defining a basic command-line interface and a `c`-format `API`. 
    Higher-level scripting interfaces, supporting a range of additional 
    facilities for file I/O, mesh visualisation and post-processing 
    operations are also available, including for `MATLAB` / `OCTAVE` 
    (https://github.com/dengwirda/jigsaw-matlab) and for `PYTHON`
    (https://github.com/dengwirda/jigsaw-python).
  doc_url: https://github.com/dengwirda/jigsaw
  dev_url: https://github.com/dengwirda/jigsaw

extra:
  recipe-maintainers:
    - xylar
    - dengwirda
