travis:
  secure:
    BINSTAR_TOKEN: M3m3QMurK3m1JUZovLh65Jk4ti9ooaEGhwaejTsr5zXCmnFnEalq4sCRjI1jGO2olM0XVxrspqqCwZrtXm473jaFxVws4EUE5uFLHn2ZmteCrF9ABrORxPl4+CX8W6sFz8+22MsnJNqjOBLFXemRZ57HfE6JpuQb3tmfVPXu1pORmWqlGg8s7PkLhAoZ1ksb5+gkYWoHW30Dsv53t7e+e54g0R6ThEupY7+0ZnGyERfjwP5CR+wuPtDUIe67utJKVixbP3dRcNjG1Z3XPDFiRFlPaYyaxrpLY5RxbE0AcgDPnl+NxXfgGh0ZXmdBwQYSIjkwrX2EXpzvdkCaujeCksIuNBAPdMBJPKvvgsIHKHOXXIG03lN8JrJQZNoM9pgYLyzCngYfMKBd/ZejMYFmYtPns9FlmVDYNC4dtnSHe9NbF+W+mCe6y1F9mSO/6jKAA1fiyqBWXezgo3D/bFE5A9XLQfCqUMU3YAOy/Xc8P2nWf4EvS4m+ZgY1PycgAKigiKdGq/0mYoYfwuQZnwipUqvTusjMzGY8MKM0cX3f5Ass+CI5Bvg58IsjlzkpSMbbF2HzkdKoUE2tIhl0/mLRT9HerWB3dc0uGJaYvlZJmDdeZRX/vwEV/ALM+1dhG5+YQRvzbyqlFYr2JaPHXDOuLvr16tmx7jnNPPJPorLcDCE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
